### ISSUE TITLE
how to automatically allign the figures when add new staff?

### ISSUE THREAD

**Issue by ShixiangWang** [CloudCannon/urban-jekyll-template#6]
Hi,
Thanks for your great work, I really like the theme. A question occur when I add a new member and the figure is not right as you set default. How can configure this?

<http://punchy-mantis.cloudvent.net/about/>

**Comment by ShixiangWang** [comment]
I find that if the figure's number is even, it's right. If the figure's number is odd, the last figure will have a bad view.

**Comment by mneumegen** [comment]
Hi there,

Have a look at [these options](https://stackoverflow.com/questions/25514579/css-keep-all-flexbox-children-elements-the-same-size) for flexbox.
